apiVersion: v1
kind: Service
metadata:
  labels:
    app: capstone
  name: capstone
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: capstone