apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: capstone
spec:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: capstone
