---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: capstone
  name: dev-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["create", "list", "get", "update", "delete"]