---
# tasks file for deployments
- name: Copy deploy directory to remote
  become: true
  ansible.builtin.copy:
    src: ../../../../deploy
    dest: /root
    owner: root
    group: root
    mode: '0750'
  tags:
    - deploy

- name: Print out the namespace before using it
  ansible.builtin.debug:
    msg: "{{ app_namespace }}"

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ app_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Apply Postgres configuration
  kubernetes.core.k8s:
    state: present
    src: /root/deploy/postgres-config.yaml
    namespace: "{{ app_namespace }}"
  tags:
    - deploy
    - apply

- name: Apply Postgres Persistent Volume Claim
  kubernetes.core.k8s:
    state: present
    src: /root/deploy/postgres-pvc-pv.yaml
    namespace: "{{ app_namespace }}"
  tags:
    - deploy
    - apply

- name: Apply Postgres deployment
  kubernetes.core.k8s:
    state: present
    src: /root/deploy/postgres-deployment.yaml
    namespace: "{{ app_namespace }}"
  tags:
    - deploy
    - apply

- name: Create Postgres Service
  kubernetes.core.k8s:
    state: present
    src: /root/deploy/postgres-service.yaml
    namespace: "{{ app_namespace }}"
  tags:
    - deploy
    - apply

- name: Create capstone deployment
  kubernetes.core.k8s:
    state: present
    src: /root/deploy/deployment.yaml
    namespace: "{{ app_namespace }}"
  tags:
    - deploy
    - apply

- name: Create capstone service
  kubernetes.core.k8s:
    state: present
    src: /root/deploy/capstone-service.yaml
    namespace: "{{ app_namespace }}"
  tags:
    - deploy
    - apply

- name: Define HorizontalPodAutoscalar
  kubernetes.core.k8s:
    state: present
    src: /root/deploy/capstone-hpa.yaml
    namespace: "{{ app_namespace }}"
  tags:
    - deploy
    - apply

