---
- name: Install Kubernetes on worker_nodes
  hosts: worker_nodes
  become: true
  vars_files:
    - vars/default.yaml
  tasks:
    - name: Apt update and apt upgrade, install packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
    - name: Update to use aptitude
      ansible.builtin.apt:
        name: aptitude
        update_cache: true
        state: latest
        force_apt_get: true

    - name: Install packages that allow apt to be used over HTTPS
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - zip
          - unzip
          - gnupg-agent
          - software-properties-common

    - name: Add an apt signing key for Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{
          ansible_distribution_release }} stable
        state: present
    - name: Install docker and its dependecies
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - docker status

    - name: Copy the join command to server location
      ansible.builtin.copy:
        src: join-command
        dest: /tmp/join-command.sh
        mode: "0777"
      tags:
        - join

    - name: Join the node to cluster
      ansible.builtin.command: sh /tmp/join-command.sh
      tags:
        - join

  handlers:
    - name: docker status
      service: name=docker state=started
